---
title: "Correct the dielectric response of GT water"
header-includes:
   - \usepackage{bm}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To correct the discrepancy of the dipole-dipole correlation function at $k=0$ between GT water and full water, I think we need to add an instantaneous uniform electric field that is in the opposite direction to the total dipole of the system. Intuitively this could suppress the too strong dipole-dipole correlation at $k=0$ for GT water. The field should have the following expression
$$
E_z = -\frac{1}{\epsilon_0} \frac{M_z}{V}\,,
$$
where $V$ is the volume of the system. $M_z$ is the total dipole momentum along the z direction. $E_z$ is the electric field.

The contribution of this term to energy (or Hamiltonian) is 
$$
E_z \sum_i q_i z_i = E_z M_z = -\frac{1}{\epsilon_0} \frac{M_z^2}{V}\,.
$$
If we write $E_z$ in the common unit where $1/4\pi\epsilon_0 = 1$. It should be
$$
E_z = -4\pi\frac{M_z}{V}\,.
$$

This term should be consistent with Zhonghan's symmetry-preserving field along $z$ direction. It should also be consistent with Cox's slab geometry result. It should not conflict with the boundary term of Ewald summation.

In Zhonghan's 2014 ChemComm paper, he got the following field
$$
E_z = -\frac{4\zeta L_z}{\sigma} \frac{M_z}{V} \,.
$$
I still don't understand how the paramter $\zeta$ came out. But when $\zeta = \pi\sigma/L_z$ the result will be consistent with my result. Zhonghan claim that error of the expansion scales as $e^{-(\pi/\zeta - L_z/\sigma)^2}$. So at this particular point, the error scales as 1, what does this mean?






$D$ is the dielectric displacement field, which can be thought as generated by free charges. 

In dielectric medium, $D$ can be defined as
$$
D = \epsilon_0 E + P \,,
$$
where $P = M/V$ is the polarization density.

$P$ depends linearly on $E$:
$$
P = \epsilon_0 \chi E
$$
where $\chi$ is the susceptibility. ($P$ and $E$ is along the same direction).

Therefore $D = \epsilon E = (1+\chi)\epsilon_0 E$. 

In Cox, he also defined external suspetibility, which is different from the suspetiblity defined above. In Cox's definition
$$
P = \epsilon_0 \chi \xi \,,
$$

where $\xi$ is the external electric field. $\xi$ might be more easily measurable in reality.

When Cox is working on the simplification of LMF theory in the slab geometry, he got that
$$
\xi_R (z) = \xi(z) - 4\pi P(z)
$$
where $\xi_R (z)$ is the LMF field. $- 4\pi P(z)$ is the renormalized part of the LMF field, which is the same as the $E_z$ I derived before. 

Cox suggested that the longitudinal dipole-dipole correlation function is discontinuous at $k =0$, when $E = 0$ at the full system. This is in contrast with the GT system where the longitudinal correlation is continuous at $k = 0$. Cox also found out that the discrepancy between full and GT happens at much lower $k$ than $2\pi/\sigma$. This could suggest that the uniform polarization field will work.

Notice that the additional field $-4\pi P$ is in opposite direction to the dipole. So its effect is to reduce the dipole, or in other words, make the distance between two ions closer. So its effect should be the same as what we have in the short solvent model.

Wolf summation add an neutralizing charge on the cutoff sphere. Also implemented the error/complementary-error separation. But maybe not so relevant in our problem considered here.

Cautious under periodic boundary conditions. When an molecule is broken into two because of periodic boundary conditions, we will have dramatica abruption in the total dipole momentum. To avoid this we need to always consider the dipole of a molecule as a whole. (i.e no matter whether a molecule is broken we should always count is as a whole). Or in other words, we should always count the molecule as a whole and ignore the fact that the molecule has been broken into two. So the total dipole of the system is defined as
$$
P = \sum_i^N p_i\,,
$$

where $p_i$ is the dipole of each polar molecule. This is where the difference with the boundary term of Ewald summation comes into play. So this is very important.

The boundary term of a uniformly polarized continuum has big effect on the total energy of dipole-dipole interaction.

At any instant, if we assume the instantaneous polarization field is uniformly polarized, then the electric field acting on the origin coming from the all the dipoles will be 
$$
\bm{E} =-\int dS \frac{\bm{M}\cdot\bm{n}}{Vr^3} \bm{r} \,,
$$

where $\bm{r}$ is the vector from center of the unit box to the boundary, $\bm{n}$ is the surface normal vector, $dS$ is the infinitesimal surface aera, $\bm{M}$ is the total dipole momentum of the system. $V$ is the volume of the system.

For a system under cubic periodic boundary conditions, the above electric field will be a uniform field:
$$
\bm{E} = -\frac{4\pi \bm{M}}{3V} \,.
$$

For a system under slab geometry, the equation above will be the same as Zhonghan's SPMF field in the limit that $L_x \gg L_z$ and $L_y \gg L_z$:
$$
\bm{E} = -\frac{4\pi \bm{M}}{V} 
$$
When this limit is not reached, our field will be more general than Zhonghan's field. Especially it is worth noticing that our field will have components along $x$ and $y$ direction, while Zhonghan's field is only along $z$ direction.

To derive this, we start from the fact that the Hamiltonian of water can be written as
$$
H = H_0 + H_1
$$
where $H_1 = \frac{1}{2}\int d\bm{r}\int d\bm{r'} \rho(\bm{r}; \bm{R}) \rho(\bm{r'}; \bm{R}) v_1(|\bm{r} - \bm{r'}|)$ is the long ranged contribution to Hamiltonian.

We can approximately write $H_1$ in terms of dipole-dipole interaction. We can define the dipole density field for water
$$
\bm{p}(\bm{r}; \bm{R}) = \sum_{i=1}^N\bm{p}_i \delta(\bm{r} - \bm{r}_i) \,,
$$
where $\bm{p}_i$ is the dipole of the $i$-th water and $\bm{r}_i$ is the position of the $i$-th water. 

$H_1$ can be rewritten as 
$$
H_1 = \frac{1}{2}\int d\bm{r}\int d\bm{r'} \left( \frac{\bm{p}(\bm{r}; \bm{R}) \cdot \bm{p}(\bm{r'}; \bm{R})}{|\bm{r}-\bm{r}'|^3} - 3\frac{\bm{p}(\bm{r}; \bm{R}) \cdot (\bm{r}-\bm{r}') \bm{p}(\bm{r'}; \bm{R}) \cdot (\bm{r}-\bm{r}')}{|\bm{r}-\bm{r}'|} \right)
$$

Under the assumption of uniformly polarization, $H_1$ can be rewritten as
$$
H_1 = -\frac{1}{2} \bm{M} \cdot \bm{E}
$$